### PR TITLE
just a simple typo is now fixed

### PR DESCRIPTION
**Pull request by bappyasif**
man page => main page

### CODE REVIEW

**Comment by mrzool** [comment]
That's not a typo.

**Comment by bappyasif** [comment]
ohh it's not, been a while since i did this pr, but please feel free to enlighten me about this, so that i or admins can close this issue....

thanks @mrzool :)

**Comment by mrzool** [comment]
man page is just short for manual page in Unix lingo:

https://en.wikipedia.org/wiki/Man_page

**Comment by bappyasif** [comment]
wow!! i didnt know that, thanks @mrzool

so i better close this off then, right?

**Comment by mrzool** [comment]
Yes :)

**Comment by bappyasif** [comment]
@mrzool done, thanks :)

**Pull request closed without merging**
